Home Task1 changes
aaisha-2k9/FrontEnd pull request #1
Opened 2019-07-10 08:35 UTC by aaisha-2k9

2019-07-10 13:59 UTC, aditya365 requested changes

2019-07-10 13:59 UTC, aditya365 commented on Home.html
> +    <style type="text/css">
Separate styles from HTML page. Put them in another file and refer them here

2019-07-10 13:59 UTC, aditya365 commented on Home.html
> +            width: 1024px;
Do not hardcode width using px. You can use viewport units or percentage widths. It helps better experience when we view in multiple devices

2019-07-10 13:59 UTC, aditya365 commented on Home.html
> +        .bodyClass {
Use cabab case (ex: body-class) for class and id names instead of pascal or camel cases

2019-07-10 13:59 UTC, aditya365 commented on Home.html
> +        .newsImageClass {
give proper (understandable) names for all classes. Do not suffix with "class"

2019-07-10 13:59 UTC, aditya365 commented on Home.html
> +<!DOCTYPE html>
Format your code using inbuilt editor formatter or prettier.

2019-07-10 13:59 UTC, aditya365 commented on Home.html
> +    <div id="pageClass">
Remove id's or classes if you do not use them either for styling or in script files

2019-07-10 13:59 UTC, aditya365 commented on Home.html
> +            <table>
Use divs and spans instead of tables. Tables distort the view when opened in devices with lower viewport widths. You can style divs to get the same look

2019-07-10 13:59 UTC, aditya365 commented on Home.html
> +                    <td style="font-style:italic; font-size : 12px">
do not use inline styles. Add a class or use semantic elements

2019-07-10 13:59 UTC, aditya365 commented on Home.html
> +            <table style="border-bottom:ridge;border-bottom-color:wheat">
do not use inline styles

2019-07-10 13:59 UTC, aditya365 commented on Home.html
> +        <div id="Body" class="bodyClass">
class or id name should not confuse with standard element names. You can use something like main-container.

2019-07-10 13:59 UTC, aditya365 commented on Home.html
> +                                            <para>
Use p tag instead

2019-07-10 13:59 UTC, aditya365 commented on Home.html
> +                    <td width="25%">
use divs and style using classes

2019-07-10 13:59 UTC, aditya365 commented on Home.html
> +                                            <textarea id="txtcategory"style="width:150px;height:20px;" > </textarea>
use input=text instead of text area. Text area is used when you need multiple lines

2019-07-10 13:59 UTC, aditya365 commented on Home.html
> +                    <td width="25%">
separate subscription section. Do not merge in same row. Use separate column for it.

2019-07-10 13:59 UTC, aditya365 commented on Home.html
> +                                        <select style="width:150px">
style dropdown and subscribe fields as per mockup.

2019-07-11 20:20 UTC, aaisha-2k9 commented on Home.html
> +    <style type="text/css">
added External css file

2019-07-11 20:21 UTC, aaisha-2k9 commented on Home.html
> +            width: 1024px;
implemented with percentage values

2019-07-11 20:21 UTC, aaisha-2k9 commented on Home.html
> +        .bodyClass {
Issue has been addressed

2019-07-11 20:22 UTC, aaisha-2k9 commented on Home.html
> +        .newsImageClass {
issue has been addressed. changed the css class name to news-image

2019-07-11 20:22 UTC, aaisha-2k9 commented on Home.html
> +<!DOCTYPE html>
formatted the code

2019-07-11 20:26 UTC, aaisha-2k9 commented on Home.html
> +                                            <para>
issue has been addressed

2019-07-11 20:26 UTC, aaisha-2k9 commented on Home.html
> +                    <td width="25%">
issue has been addressed

2019-07-11 20:26 UTC, aaisha-2k9 commented on Home.html
> +                                            <textarea id="txtcategory"style="width:150px;height:20px;" > </textarea>
issue has been addressed

2019-07-12 09:05 UTC, merged